### PR TITLE
Add ability to connect Susi Webclient to Susi Hardware

### PR DESCRIPTION
**Pull request by betterclever**
Initial Steps for Issue #26 

**What's working?**
A WebSocket server is made to run on ws://127.0.0.1:5678 which send all the queries from Susi Hardware device like a Raspberry Pi to the socket. A client can listen on this interface  ws://127.0.0.1:5678  to get queries.

**What I am working on currently?**
- Adding ability to receive Susi JSON response through websocket which will be sent via client. It is need so that only one API call is made to Susi Server.
- Refactoring code for Readability. 

**Updates:**
- Modified the Websocket library to https://github.com/Pithikos/python-websocket-server . Were having issues in previous library.
- Added JSON Support , now JSON is sent via modified Susi_webchat client to Susi Hardware and response is parsed there. Link to that will be added here. 
Link to changes in Susi Webchat (not synced with upstream, needs a little change) https://github.com/betterclever/chat.susi.ai/commit/42b8f1f3b1c0eaa46b1afcf78e6137f4e73970ea
- Port for WebSocket changed to 9001 from 5678

### CODE REVIEW

**Comment by rishiraj824** [comment]
@betterclever will try to reproduce this in my local.

**Comment by betterclever** [comment]
@rishiraj824 I have added some details and modified implementation.

**Comment by rishiraj824** [comment]
@betterclever Sure will check them out, 👍

**Comment by betterclever** [comment]
This part is complete. I think we should merge this and continue rest of the implementation in an other issue and PR. Rest of the implementation include ability to switch to "webchat Interactive connect" mode upon press of a key. 
I shall open an issue for that. 

@chiragw15 @rishiraj824 @uday96 please review.

**Comment by rishiraj824** [comment]
@betterclever Please check out https://github.com/fossasia/chat.susi.ai/pull/286

**Comment by betterclever** [comment]
@mariobehling Please merge.

**Pull request merged**
